# License Key
LICENSE-KEY: "PUT-HERE-YOUR-LICENSE-KEY"

# Command Settings
COMMAND_SETTINGS:
  NAME: "sanction"
  PERMISSION: litebans.ban
  ALIASES:
    - "sancion"
    - "sancionar"
    - "bangui"

# Sanction Settings
SANCTION_SETTINGS:
  BAN_COMMAND: "ban -s <player> <reason>"
  TEMPBAN_COMMAND: "tempban -s <player> <duration> <reason>"
  MUTE_COMMAND: "mute -s <player> <reason>"
  TEMP_MUTE_COMMAND: "tempmute -s <player> <duration> <reason>"
  WARN_COMMAND: "warn -s <player> <reason>"
  HISTORY_COMMAND: "history <player>"